version: '2'
services:
  redis:
    image: redis:5.0.0
    container_name: redis
    command: redis-server --requirepass 123456
    ports:
      - "16379:6379"
    volumes:
      - ./data:/data # 存放redis持久化数据
# 单机版本